apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: docker-debug
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: docker-debug
